# Generated by Django 5.2.8 on 2025-11-15 09:34

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_app_icon_alter_appcategory_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, default=None, upload_to=main.models.app_path),
        ),
    ]
