# Generated by Django 5.2.8 on 2025-11-15 09:49

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_app_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.TextField(default=main.models.generate_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
