# Generated by Django 5.2.8 on 2025-11-15 09:58

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='downloads',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='app',
            name='estimations_count',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, upload_to=main.models.app_path),
        ),
        migrations.AlterField(
            model_name='app',
            name='rating',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='app',
            name='views',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='appcategory',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appcategory',
            name='icon',
            field=models.ImageField(blank=True, upload_to=main.models.icon_path),
        ),
        migrations.AlterField(
            model_name='appdeveloper',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=main.models.app_developer_path),
        ),
        migrations.AlterField(
            model_name='appdeveloper',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appdeveloper',
            name='id',
            field=models.TextField(default=main.models.generate_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appsubcategory',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appsubcategory',
            name='icon',
            field=models.ImageField(blank=True, upload_to=main.models.icon_path),
        ),
    ]
